backend:
  name: git-gateway
  branch: main

media_folder: static/img
public_folder: /img

collections:
  - name: "infos"
    label: "Aktuelles"
    format: "json"
    folder: "content/infos"
    create: false
    slug: "{{slug}}"
    editor:
      preview: true
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Body", name: "description", widget: "markdown" }
  - name: "sidebar"
    label: "Seiten Navigaion"
    format: "json"
    folder: "content/sidebarNav"
    create: true
    slug: "{{slug}}"
    editor:
      preview: true
    fields:
      - { label: "Überschrift", name: "title", widget: "string" }
      - { label: "Untertitel", name: "subtitle", widget: "string" }
      - { label: "Link Text", name: "linkText", widget: "string" }
      - { label: "Link Adresse", name: "link", widget: "string" }
      - { label: "Beschreibung", name: "description", widget: "markdown" }
  - name: "speisekarten"
    label: "Speisekarten"
    format: "json"
    folder: "content/menu"
    create: true
    slug: "{{slug}}"
    widget: "list"
    editor:
      preview: true
    fields:
      - { label: "Überschrift", name: "title", widget: "string" }
      - { label: "Publish Date", name: "date", widget: "datetime" }
      - label: "Speisen"
        name: "speisen"
        widget: "list"
        fields:
          - {label: Gericht, name: food, widget: string }
          - {label: Beilage (Optional), name: garnish, widget: string }
          - {label: Preis, name: price, widget: number }