backend:
  name: git-gateway
  branch: main

publish_mode: editorial_workflow

media_folder: static/
public_folder: /img

collections:
  - name: "content"
    label: "Kommunikation"
    format: "json"
    folder: "content/content"
    create: false
    slug: "{{slug}}"
    editor:
      preview: true
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Body", name: "content", widget: "markdown", required: false }
      - { label: "Reihenfolge", name: "order", widget: "number", required: false }
  - name: "portfolio"
    label: "Portfolio"
    format: "json"
    folder: "content/portfolio"
    create: true
    slug: "{{slug}}"
    editor:
      preview: true
    fields:
      - { label: "Titel", name: "title", widget: "string" }
      
  - name: "portfolioLogos"
    label: "Portfolio Logos"
    format: "json"
    folder: "content/portfolioLogos"
    create: true
    slug: "{{slug}}"
    editor:
      preview: true
    fields:
      - { label: "Titel", name: "title", widget: "string" }
  - name: "team"
    label: "Team"
    format: "json"
    folder: "content/team"
    create: true
    slug: "{{slug}}"
    editor:
      preview: true
    fields:
      - { label: "Vorname Nachname", name: "title", widget: "string" }