backend:
  name: git-gateway
  branch: main

publish_mode: editorial_workflow

media_folder: static/
public_folder: /img

collections:
  - name: "content"
    label: "Kommunikation"
    format: "json"
    folder: "content/content"
    create: false
    slug: "{{slug}}"
    editor:
      preview: true
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Body", name: "content", widget: "markdown", required: false }
      - { label: "Reihenfolge", name: "order", widget: "number", required: false }
  - name: "portfolio"
    label: "Portfolio"
    format: "json"
    folder: "content/portfolio"
    create: true
    slug: "{{slug}}"
    editor:
      preview: true
    fields:
      - { label: "Titel", name: "title", widget: "string" }
      - label: "Bild"
        name: "src"
        widget: "image"
        required: false
        config: 
          media_folder: "{{slug}}"
      - { label: "Kurzbeschreibung", name: "content", widget: "markdown", required: false }
      - { label: "Url", name: "link", widget: "string", required: false }
      - { label: "Beschreibung", name: "description", widget: "markdown", required: false}
  - name: "portfolioLogos"
    label: "Portfolio Logos"
    format: "json"
    folder: "content/portfolioLogos"
    media_folder: "{{slug}}"
    create: true
    slug: "{{slug}}"
    editor:
      preview: true
    fields:
      - { label: "Titel", name: "title", widget: "string" }
      - label: "Bild"
        name: "src"
        widget: "image"
        required: false
        choose_url: true
  - name: "team"
    label: "Team"
    format: "json"
    folder: "content/team"
    media_folder: "{{slug}}"
    create: true
    slug: "{{slug}}"
    editor:
      preview: true
    fields:
      - { label: "Vorname Nachname", name: "title", widget: "string" }
      - { label: "Job Titel", name: "jobTitle", widget: "string", required: false }      
      - { label: "Email", name: "email", widget: "string", required: false } 
      - label: "Bild"
        name: "image"
        widget: "image"
        required: false
        choose_url: true
      - { label: "Reihenfolge", name: "order", widget: "number", required: false }
      - { label: "Hervorgehoben", name: "featured", widget: "boolean", required: false }
      