backend:
  name: git-gateway
  branch: main

local_backend: true

publish_mode: editorial_workflow

media_folder: static/
public_folder: /

collections:
  - name: "content"
    label: "Kommunikation"
    format: "json"
    folder: "content/content"
    create: false
    slug: "{{slug}}"
    editor:
      preview: true
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Body", name: "content", widget: "markdown", required: false }
      - {
          label: "Reihenfolge",
          name: "order",
          widget: "number",
          required: false,
        }
  - name: "portfolio"
    label: "Portfolio"
    format: "json"
    folder: "content/portfolio"
    create: true
    slug: "{{slug}}"
    editor:
      preview: true
    media_folder: /static/portfolio
    fields:
      - { label: "Titel", name: "title", widget: "string" }
      - label: "Bild"
        name: "src"
        widget: "image"
        required: false
        media_library:
          collection:
            name: "portfolio"
      - {
          label: "Kurzbeschreibung",
          name: "content",
          widget: "markdown",
          required: false,
        }
      - { label: "Url", name: "link", widget: "string", required: false }
      - {
          label: "Beschreibung",
          name: "description",
          widget: "markdown",
          required: false,
        }
  - name: "portfolioLogos"
    label: "Portfolio Logos"
    format: "json"
    folder: "content/portfolioLogos"
    create: true
    slug: "{{slug}}"
    editor:
      preview: true
    media_folder: /static/portfolioLogos
    fields:
      - { label: "Titel", name: "title", widget: "string" }
      - label: "Bild"
        name: "src"
        widget: "image"
        required: false
        choose_url: true
        media_library:
          collection:
            name: "portfolioLogos"
  - name: "team"
    label: "Team"
    format: "json"
    folder: "content/team"
    create: true
    slug: "{{slug}}"
    editor:
      preview: true
    media_folder: /static/team
    fields:
      - { label: "Vorname Nachname", name: "title", widget: "string" }
      - {
          label: "Job Titel",
          name: "jobTitle",
          widget: "string",
          required: false,
        }
      - { label: "Email", name: "email", widget: "string", required: false }
      - label: "Bild"
        name: "image"
        widget: "image"
        required: false
        choose_url: true
        media_library:
          collection:
            name: "team"
      - {
          label: "Reihenfolge",
          name: "order",
          widget: "number",
          required: false,
        }
      - {
          label: "Hervorgehoben",
          name: "featured",
          widget: "boolean",
          required: false,
        }
  - name: "contact"
    label: "Kontakt"
    format: "json"
    folder: "content/contact"
    create: true
    slug: "{{slug}}"
    editor:
      preview: true
    fields:
      - { label: "Titel", name: "title", widget: "string" }
      - { label: "Firma", name: "company", widget: "string" }
      - { label: "Strasse", name: "street", widget: "string" }
      - { label: "City", name: "city", widget: "string"}
      - { label: "Email", name: "email", widget: "string" }
      - { label: "Telefon", name: "phone", widget: "string" }
      - { label: "Karte", name: "location", widget: "map" }