backend:
  name: git-gateway
  branch: main

publish_mode: editorial_workflow

media_folder: static/img
public_folder: /img

collections:
  - name: "infos"
    label: "Aktuelles"
    format: "json"
    folder: "content/infos"
    create: false
    slug: "{{slug}}"
    editor:
      preview: true
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Body", name: "content", widget: "markdown" }
  - name: "sidebar"
    label: "Seiten Navigaion"
    format: "json"
    folder: "content/sidebarNav"
    create: true
    slug: "{{slug}}"
    editor:
      preview: true
    fields:
      - { label: "Überschrift", name: "title", widget: "string" }
      - { label: "Untertitel", name: "subtitle", widget: "string" }
      - { label: "Link Text", name: "linkText", widget: "string" }
      - { label: "Link Adresse", name: "link", widget: "string" }
      - { label: "Beschreibung", name: "description", widget: "markdown" }
  - name: "speisekarten"
    label: "Speisekarten"
    format: "json"
    folder: "content/menu"
    create: true
    slug: "{{slug}}"
    editor:
      preview: true
    fields:
      - { label: "Name der Speisekarte", name: "title", widget: "string" }
      - label: "Speisen"
        name: "speisen"
        widget: "list"
        add_to_top: true
        fields:
          - {label: Gericht, name: food, widget: string }
          - {label: Beilage (Optional), name: garnish, widget: string, required: false }
          - {label: Preis, name: price, widget: number, value_type: "float" }
  - name: "mittagstisch"
    label: "Mittagstisch"
    format: "json"
    folder: "content/mittagstisch"
    create: true
    slug: "{{slug}}"
    editor:
      preview: true
    fields:
      - { label: "Name der Speisekarte", name: "title", widget: "string" }
      - { label: "Untertitel(optional)", name: "subtitle", widget: "string", required: false }
      - label: "Platzierung (Optional)",
        name: "placed",
        widget: "widget",
        options:
          - { label: "Startseite", value: "Startseite" }
      - label: "Speisen"
        name: "speisen"
        widget: "list"
        description: "Auswählen wenn das Menü auf der Startseite gezeigt werden soll."
        add_to_top: true
        fields:
          - {label: Gericht, name: food, widget: string }
          - {label: Beilage (Optional), name: garnish, widget: string, required: false }
          - {label: Preis, name: price, widget: number, value_type: "float" }
  - name: "important"
    label: "Wichtige Seiten"
    format: "markdown"
    folder: "content"
    create: true
    slug: "{{slug}}"
    editor:
      preview: true
    fields:
      - { label: "Überschrift", name: "title", widget: "string" }
      - { label: "Beschreibung", name: "description", widget: "markdown" }